# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FrameNet-WordNet-Detour
version:      0.97
version_from: lib/FrameNet/WordNet/Detour.pm
installdirs:  site
requires:
    Class::MethodMaker:            2
    File::Spec:                    0.86
    Getopt::Long:                  2.34
    Pod::Usage:                    1
    Test::More:                    0
    WordNet::QueryData:            1.37
    WordNet::Similarity::path:     0.1
    XML::TreeBuilder:              3.09

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
